server:
  port: 8080

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        prefetch: 10
        consumers-per-queue: 10
      type: direct

rabbitmq:
  dead:
    letter:
      retry-max: 3